CREATE DATABASE IF NOT EXISTS OFICINA_SAEP_DB;
USE OFICINA_SAEP_DB;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS VEICULO(
	VEI_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEI_NOME VARCHAR(100) NOT NULL,
    VEI_DATA_FABRICACAO DATE NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AGENDAMENTO(
	AGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    AGE_SERVICO VARCHAR(100) NOT NULL,
    AGE_DATA_HORA DATETIME NOT NULL,
    AGE_STATUS VARCHAR(30) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FK_VEI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_VEI_ID) REFERENCES VEICULO(VEI_ID) ON DELETE CASCADE
);

INSERT INTO USUARIO(USU_NOME, USU_EMAIL, USU_SENHA) VALUES
("Admin", "admin@admin.com", "admin123"),
("Gabriel", "gabriel@email.com", "123456"),
("Luiz", "luiz@email.com", "123456");

INSERT INTO CLIENTE(CLI_NOME, CLI_DATA_NASCIMENTO) VALUES
("Gabriel", "2000-07-16"), 	-- RES_ID - 1
("Luiz", "1800-01-01"), 	-- RES_ID - 2
("Leonardo", "1998-10-10"); -- RES_ID - 3

INSERT INTO VEICULO(VEI_NOME, VEI_DATA_FABRICACAO, FK_CLI_ID) VALUES
("Fusca", "2024-04-05", 2), 	-- PAC_ID - 1
("BMW", "2024-05-17", 1), 	-- PAC_ID - 2
("Corola", "2020-10-01", 3); 		-- PAC_ID - 3

INSERT INTO AGENDAMENTO(AGE_DATA_HORA, AGE_SERVICO, AGE_STATUS, FK_VEI_ID, FK_CLI_ID) VALUES
("2026-09-26 08:00:00", "Limpeza", "Agendada", 1, 2), 	
("2026-09-26 08:30:00", "Blindagem", "Agendada", 2, 1),
("2026-09-26 09:00:00", "Limpeza interna", "Agendada", 3, 3);